# .github/workflows/sync.yml

name: Sync Fork

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 10 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: zwping/fork-sync@v1.6.5
        with:
          owner: leejoker
          retries: 10
